### ISSUE TITLE
Sensors records table page template

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/smart-farming#28]
- Create a page template to show a table which will list all sensors records for each row.
- The design of the table should follow Figma prototype.
-  The table should show buttons for pagination.
-  A checkbox input should be before each row of the table .
- Try mocking data to test the table.

**Comment by JohnPetros** [comment]
- Create a page template to show a table which will list all sensors records for each row.
- The design of the table should follow Figma prototype.
-  The table should show buttons for pagination.
-  A checkbox input should be before each row of the table .
- Try mocking data to test the table.

**Comment by 0thigs** [comment]
Ain Gozei
