### ISSUE TITLE
Get sensors dashboard page data use case

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/smart-farming#31]

**Comment by kaufon** [comment]
Can you please explain?

Thought i was assigned create data filter by date for now

**Comment by JohnPetros** [comment]
@kaufon the filtered by date data is the data the sensors dashboard page will need to render the charts

**Comment by JohnPetros** [comment]
You should create a dictionary with the keys:
- 7 days
- 30 days
- 90 days

each value of the key should be a list of sensors records like:

```python
{
  "7 days": [],
  "30 days": [],
  "90 days": [],
}
```
