### ISSUE TITLE
Datetime Common

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/smart-farming#58]
# Tasks
- Create a Common called `Datetime`.
- Do the datetime formatting inside a method called `get_value` which should return the datetime passed to `Datetime` `__init__ ` method.
- Use the `Datetime` common inside SensorsRecord entity ` __post_init_ ` method like:
```python
@dataclass
class SensorsRecord(Entity):
    soil_humidity: int = None
    ambient_humidity: int = None
    temperature: int = None
    water_volume: int = None
    created_at: Datetime = None

   def __post_init__(self) -> None:
   
        if self.created_at is not None:
            datetime = Datetime(self.created_at)
            self.created_at = datetime.get_value()

```

**Comment by kaufon** [comment]
but why do this if it can be done by simply formated by doing date.strftime("%d-%m-%Y %H:%M:%S")

**Comment by JohnPetros** [comment]
Because Datetime will be use for the checklist records too so you will need write date.strftime("%d-%m-%Y %H:%M:%S") only once
