### ISSUE TITLE
Plant form

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/smart-farming#68]
## Tasks
- Create a template to include the form that will be used to create and delete a plant.
- The form should have the fieds:
  - name (text type input)
  - color (color type input) which will demand a hack to be styled

[Design on Figma](https://github.com/CtrI-Alt-Del/smart-farming/blob/main/documentation/images/planta2_desktop.png)

**Comment by kaufon** [comment]
banana ta de parabuians
